### ISSUE TITLE
add option to lock forums away to only registered users

### ISSUE THREAD

**Issue by Lana-chan** [transbian-alliance/lesbiaboard#1]
right now there's only a setting for power level to determine whether someone can read a forum or not -- and power levels in of themselves are horribly hardcoded right now.

something needs to be added to allow forums to be hidden to unregistered guests as well

**Comment by Pululut** [comment]
There's at least one piece of code that references this was planned at some point in makeForumListing(), but is otherwise completely unused and the column doesn't exist...

**Comment by Lana-chan** [comment]
solved by 98767e3f6cb333bc67cafd76bfca478e3c7436bb
