### ISSUE TITLE
More in-depth installation instructions?

### ISSUE THREAD

**Issue by Fidgetcetera** [transbian-alliance/lesbiaboard#9]
I'm looking to set up an instance of lesbiaboard for my friends, and the install instructions are... Not the clearest. The automatic installer gets to here: 
![image of the SQL screen of the installer, with default values](https://user-images.githubusercontent.com/15249812/94609826-57a42c80-026d-11eb-8b62-9345539d1e91.png)

but no part of instructions super indicates what i should be doing wrt setting up... presumably a mysql server??? and just hitting next with the defaults can't connect, of course. 
Sorry, maybe we're just too new and terrible of ~~sys~~transadmins, but we're kinda confused.

**Comment by Lana-chan** [comment]
you need to set up a SQL server (mysql, postgres, etc) of your choice and create a database and a set of credentials that can edit said database, then input those values in that box. setting up a SQL server is beyond the scope of our guide, there are many tutorials online

**Comment by Fidgetcetera** [comment]
> setting up a SQL server is beyond the scope of our guide, there are many tutorials online

that's reasonable! but it could probably at least be stated that you do need one and that there's not any automatic setup in that area.
